-- CREATING THE public SCHEMA
CREATE SCHEMA IF NOT EXISTS public;

-- CREATING USERS TABLE FOR THE APPLICATION
CREATE TABLE IF NOT EXISTS users (
first_name VARCHAR(100),
id VARCHAR(INT),
last_name VARCHAR(255));